apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager.fullname" . }}-staging
  labels:
{{ include "cert-manager.labels" . | indent 4 }}
spec:
  acme:
    server: https://acme-staging-v2.api.letsencrypt.org/directory
    email: {{ .Values.letsencryptEmail }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.cloudflareEmail }}
            apiKeySecretRef:
              {{ if .Values.existingSecret -}}
              name: {{ .Values.existingSecret }}
              {{ else -}}
              name: {{ include "cert-manager.fullname" . }}-cloudflare
              {{ end -}}
              key: {{ default "api_key" .Values.existingSecretAPiKeyName }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager.fullname" . }}-production
  labels:
{{ include "cert-manager.labels" . | indent 4 }}
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: {{ .Values.letsencryptEmail }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.cloudflareEmail }}
            apiKeySecretRef:
              {{ if .Values.existingSecret -}}
              name: {{ .Values.existingSecret }}
              {{ else -}}
              name: {{ include "cert-manager.fullname" . }}-cloudflare
              {{ end -}}
              key: {{ default "api_key" .Values.existingSecretAPiKeyName }}      