apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiddlywiki.fullname" . }}
  labels:
{{ include "tiddlywiki.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tiddlywiki.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tiddlywiki.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TIDDLYWIKI_PORT
              value: "80"
            - name: TIDDLYWIKI_DIR
              value: /data
            - name: TIDDLYWIKI_NAME
              name: {{ .Values.server_name }}
            {{- if .Values.credsFromSecret.enabled }}
            - name: TIDDLYWIKI_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credsFromSecret.secret }}
                  key: {{ .Values.credsFromSecret.userKey }}
            - name: TIDDLYWIKI_PASSWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credsFromSecret.secret }}
                  key: {{ .Values.credsFromSecret.passwordKey }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "tiddlywiki.name" . }}-storage
              mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "tiddlywiki.name" . }}-storage
          {{- if .Values.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "tiddlywiki.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}