{{ range $client := .Values.keycloak.clients -}}
{{ if not $client.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" $ }}-{{ $client.clientId }}-client-secret
type: Opaque
stringData:
  client_id: {{ $client.clientId }}
  client_secret: {{ randAlphaNum 10 }}
  cookie_secret: {{ randAlphaNum 10 }}
{{ end -}}
{{ end -}}