# Default values for oauth2-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replicas per deployment
replicaCount: 1
# Range of deployments
maxReplicas: 5
minReplicas: 1

image:
  repository: bitnami/oauth2-proxy
  tag: 3.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

existingSecret: ''
existingSecretClientIDKey: 'client_id'
existingSecretClientSecretKey: 'client_secret'
existingSecretCookieSecretKey: 'cookie_secret'

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 50m
  #   memory: 128Mi
  # requests:
  #   cpu: 10m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
