apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
{{ include "oauth2-proxy.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oauth2-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oauth2-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: oauth2-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: 
            - --cookie-domain="{{ .Values.cookieDomain }}"
            # name of this cookie is also referenced in Ingresses (cookie split issue)
            - --cookie-name=auth
            - --cookie-refresh=1h
            - --cookie-secure=true
            - --email-domain='*'
            - --http-address=0.0.0.0:4180
            - --oidc-issuer-url=https://{{ .Values.issuerDomain }}/auth/realms/{{ .Values.realm }}
            - --pass-access-token=true
            - --provider=oidc
            - --set-xauthrequest=true
            - --tls-cert=
            - --upstream=file:///dev/null
            # remove for prod cluster issuer
            - --ssl-insecure-skip-verify=true
          ports:          
            - containerPort: 4180
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
          initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "oauth2-proxy.client-secret-name" . }}
                  key: {{ default "client_id" .Values.existingSecretClientIDKey }}
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oauth2-proxy.client-secret-name" . }}
                  key: {{ default "client_secret" .Values.existingSecretClientSecretKey }}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oauth2-proxy.client-secret-name" . }}
                  key: {{ default "cookie_secret" .Values.existingSecretCookieSecretKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
