{{- if len .Values.resources -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "oauth2-proxy.fullname" . }}
  targetCPUUtilizationPercentage: 50
{{- end -}}