{{ if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.client-secret-name" . }}
type: Opaque
stringData:
  client_id: oauth2-proxy
  client_secret: {{ randAlphaNum 10 }}
  cookie_secret: {{ randAlphaNum 10 }}
{{- end -}}